# Phase 1 Project 

This project is designed to ..... from a flight dataset, which contains...

### 1. Setup & Configuration

In [47]:
# Import important librabries needed 

# Data Handling 
import pandas as pd
import numpy as np

# Visualization
import matplotlib
import matplotlib.pyplot as plt

# Configure notebook display settings
%matplotlib inline
plt.rcParams['figure.figsize'] = (12, 8) # Set default figure size for plots

### 2. Data Ingestion

In [48]:
# Path to the dataset obtained from Kaggle

# Path to Excel file
file_path = './flight.csv'

# Load the dataset into a pandas DataFrame
flight_df = pd.read_csv(file_path, index_col=0) # remove index column if not needed

flight_df.head()  # Display the first few rows of the DataFrame

,acc.date,type,reg,operator,fat,location,dmg
0,3 Jan 2022,British Aerospace 4121 Jetstream 41,ZS-NRJ,SA Airlink,0,near Venetia Mine Airport,sub
1,4 Jan 2022,British Aerospace 3101 Jetstream 31,HR-AYY,LANHSA - Línea Aérea Nacional de Honduras S.A,0,Roatán-Juan Manuel Gálvez International Airpor...,sub
2,5 Jan 2022,Boeing 737-4H6,EP-CAP,Caspian Airlines,0,Isfahan-Shahid Beheshti Airport (IFN),sub
3,8 Jan 2022,Tupolev Tu-204-100C,RA-64032,"Cainiao, opb Aviastar-TU",0,Hangzhou Xiaoshan International Airport (HGH),w/o
4,12 Jan 2022,Beechcraft 200 Super King Air,NaN,private,0,"Machakilha, Toledo District, Grahem Creek area",w/o

### 3. Data Profiling / Initial Inspection

In [49]:
# Print the shape of the DataFrame (rows, columns)
print(f"df shape: {df.shape}")

df shape: (2500, 7)

#### 3.1 Check for null values and fix it

In [50]:

flight_df.isnull().sum()

acc.date     0
type         0
reg         92
operator    14
fat         12
location     0
dmg          0
dtype: int64

We have a 92 missing values from reg, 14 from opertor and 12 from fat. We have two options:

1. Fill in missing values:
    - Relpace the missing values with appropriate "Unkown"  that enables us to maintain data integrity and allows us to keep all rows without loosing data for better analysis

2. Drop Rows with missing values 
    - Remove all rows with missing data that keeps the analysis clean and focused on known data. The downside is that I lose potentially valuable data and reduce the dataset size

In this project, **option 2** is the best due to reliability.

3.1.1 Working on missing Values for Reg

In [51]:
# Sample 5 rows where 'reg' column is not null
has_reg = flight_df[flight_df["reg"].notna()].sample(5)
has_reg

,acc.date,type,reg,operator,fat,location,dmg
1228,1 Dec 2018,Airbus A320-232 (WL),N632NK,Spirit Airlines,0,"near Las Vegas, NV",non
1206,12 Oct 2018,Boeing 737-8HG (WL),VT-AYD,Air India Express,0,Tiruchirappalli-Civil Airport (TRZ),sub
428,25 Dec 2021,Airbus A330-343,C-GFAF,Air Canada,0,Montreal-Pierre Elliott Trudeau International ...,sub
549,8 Jun 2020,Lockheed C-130H3 Hercules,94-6706,United States Air Force - USAF,0,Al Taji Army Air Field (ORTI),sub
896,11 Oct 2019,de Havilland Canada DHC-6 Twin Otter 100,N166DH,Skydive Georgia,0,"Cedartown-Polk County Airport, GA",sub

In [52]:
# Sample 5 rows where 'reg' column is null
no_reg = flight_df[flight_df["reg"].isna()].sample(5)
no_reg

,acc.date,type,reg,operator,fat,location,dmg
435,31 Dec 2021,IRMA/Pilatus Britten-Norman BN-2T Islander,NaN,Royal Moroccan Gendarmerie,0,off N'Tireft,unk
986,25 Jan 2018,Airbus A320,NaN,Unknown,0,Berlin-Schönefeld Airport (SXF/EDDB),sub
954,18 Dec 2019,Beechcraft 200 Super King Air,NaN,private,0,"El Chico, Retalhuleu",w/o
821,30 Jul 2019,unknown,NaN,Fuerza Aérea de Guinea Ecuatorial,0,off Grand Batanga,w/o
1237,8 Dec 2018,Beechcraft 200 Super King Air,NaN,Unknown,0,"Corozo, Sarstún",w/o

In [53]:
# Drop rows with missing 'reg' values
flight_df = flight_df.dropna(subset=['reg'])

# Check for remaining missing values
flight_df["reg"].isna().sum()

np.int64(0)

In [54]:
# Assertain that there are no missing values in 'reg' column
assert flight_df["reg"].isna().sum() == 0

3.1.2 Working on missing Values for Operator

In [55]:
# Sample 5 rows where 'operator' column is  not null
has_operator = flight_df[flight_df["operator"].notna()].sample(5)
has_operator

,acc.date,type,reg,operator,fat,location,dmg
22,21 Feb 2022,de Havilland Canada DHC-3T Texas Turbine Otter,N413JP,Bald Mountain Air Services,0,"Umiat Airport, AK (UMT)",sub
358,26 Aug 2021,Embraer EMB-505 Phenom 300,N413N,Nicholas Services LLC,0,"Elk River, NC (NC06)",sub
550,9 Jun 2020,Beechcraft 1900D,C-GSLX,Sunwest Aviation,0,"near Lac la Biche (CYLB), AB",sub
76,21 May 2022,Boeing 737-7H4 (WL),N256WN,Southwest Airlines,0,"Tacoma, Washington",non
567,10 Jul 2020,Learjet 45,XA-CAO,Aeroparadise SA,0,Toluca-Licenciado Adolfo López Mateos Internat...,sub

In [56]:
# Sample rows where 'operator' column is null
no_operator = flight_df[flight_df["operator"].isna()]
no_operator

         acc.date             type     reg operator fat          location  dmg
1015  22 Mar 2018  Airbus A320-232  VH-...      NaN   0  near Cairns, QLD  non
1015  22 Mar 2018  Airbus A320-232  VH-...      NaN   0  near Cairns, QLD  non

In [57]:
# Drop rows with missing 'operator' values
flight_df = flight_df.dropna(subset=['operator'])

# Check for remaining missing values
flight_df["operator"].isna().sum()

np.int64(0)

In [58]:
# Assertain that there are no missing values in 'operator' column
assert flight_df["operator"].isna().sum() == 0

3.1.3 Working on missing Values for Fat

In [59]:
# Sample 5 rows where 'fat' column is not null
has_fat = flight_df[flight_df["fat"].notna()].sample(5)
has_fat

,acc.date,type,reg,operator,fat,location,dmg
846,15 Aug 2019,Boeing 787-8 Dreamliner,JA808A,All Nippon Airways - ANA,0,"Over Chengde, Hebei Province",non
144,10 Sep 2022,Cessna 208B Grand Caravan,PT-MES,Piquiatuba Táxi Aéreo,1,"near Porto Trombetas, PA",w/o
142,9 Sep 2022,Cirrus SF50 Vision Jet,N77VJ,TAC9 Inc.,0,"10 km SSW of Kissimmee Gateway Airport, FL (ISM)",sub
218,31 Dec 2022,Cessna 208B Grand Caravan,5X-GBR,BAR Aviation,0,Mweya Airport (HUMW),w/o
1087,6 Jun 2018,Antonov An-2R,YR-DAX,Aeroserv,0,"Baleni, Galati County",w/o

In [60]:
# Sample 5 rows where 'fat' column is null
no_fat = flight_df[flight_df["fat"].isna()].sample(5)
no_fat

,acc.date,type,reg,operator,fat,location,dmg
658,5 Dec 2020,British Aerospace BAe-125-800A,N484AR,private,NaN,Jesús María Semprúm,w/o
30,24 Feb 2022,Antonov An-26,RF-36074,Russian Air Force,NaN,"near Ostrogozhsk, Voronezh Region",w/o
521,5 Apr 2020,Antonov An-26,UP-AN601,Libyan National Army,NaN,near Tarhuna,w/o
658,5 Dec 2020,British Aerospace BAe-125-800A,N484AR,private,NaN,Jesús María Semprúm,w/o
1223,23 Nov 2018,British Aerospace BAe-125-700A,N422X,private,NaN,S of Curaçao [Caribbean Sea],mis

In [61]:
# Drop rows with missing 'fat' values
flight_df = flight_df.dropna(subset=['fat'])

# Check for remaining missing values
flight_df["fat"].isna().sum()

np.int64(0)

In [62]:
# Assertain that there are no missing values in 'operator' column
assert flight_df["fat"].isna().sum() == 0

Confirm that there are no more null values

In [63]:
flight_df.isnull().sum()

acc.date    0
type        0
reg         0
operator    0
fat         0
location    0
dmg         0
dtype: int64

### 4. Identify Text Data that Require Cleaning

In [64]:
flight_df["type"].value_counts()

type
Cessna 208B Grand Caravan                   108
Antonov An-2R                                58
Beechcraft 200 Super King Air                40
de Havilland Canada DHC-6 Twin Otter 300     34
de Havilland Canada DHC-8-402Q Dash 8        28
                                           ...
Boeing 737-86J (WL)                           2
Boeing 767-375ER                              2
Boeing 747-412 (BCF)                          2
Boeing 747-412F (SCD)                         2
Rockwell Sabreliner 80                        2
Name: count, Length: 506, dtype: int64

There are cases where we have data entry issues, and publishers that should be encoded the same have not been. The specification of Boeing 737-86J(WL) AND bOEING 767-375ER, for example can be made into the same categories

In [65]:
# Remove leading/trailing whitespace from 'type' column
# Replace all variations to unify category names
flight_df['type'] = (
    flight_df['type']
    .str.strip()
    .replace(r'^Airbus.*', 'Airbus', regex=True)
    .replace(r'^Antonov.*', 'Antonov', regex=True)
    .replace(r'^ATR.*', 'ATR', regex=True)
    .replace(r'^Basler.*', 'Basler', regex=True)
    .replace(r'^Beechcraft.*', 'Beechcraft', regex=True)
    .replace(r'^Boeing.*', 'Boeing', regex=True)
    .replace(r'^Bombardier.*', 'Bombardier', regex=True)
    .replace(r'^British.*', 'British Aerospace', regex=True)
    .replace(r'^Britten.*', 'Britten-Norman', regex=True)
    .replace(r'^Canadair.*', 'Canadair', regex=True)
    .replace(r'^CASA.*', 'CASA', regex=True)
    .replace(r'^Cessna.*', 'Cessna', regex=True)
    .replace(r'^Cirrus.*', 'Cirrus', regex=True)
    .replace(r'^Convair.*', 'Convair', regex=True)
    .replace(r'^Dassault.*', 'Dassault', regex=True)
    .replace(r'^De Havilland.*', 'De Havilland', regex=True)
    .replace(r'^Dornier.*', 'Dornier', regex=True)
    .replace(r'^Douglas.*', 'Douglas', regex=True)
    .replace(r'^Eclipse.*', 'Eclipse', regex=True)
    .replace(r'^Embraer.*', 'Embraer', regex=True)
    .replace(r'^Fairchild.*', 'Fairchild', regex=True)
    .replace(r'^Fokker.*', 'Fokker', regex=True)
    .replace(r'^Grumman.*', 'Grumman', regex=True)
    .replace(r'^Gulfstream.*', 'Gulfstream', regex=True)
    .replace(r'^Harbin.*', 'Harbin', regex=True)
    .replace(r'^Hawker.*', 'Hawker', regex=True)
    .replace(r'^IAI.*', 'IAI', regex=True)
    .replace(r'^Ilyushin.*', 'Ilyushin', regex=True)
    .replace(r'^Learjet.*', 'Learjet', regex=True)
    .replace(r'^Let.*', 'Let', regex=True)
    .replace(r'^Lockheed.*', 'Lockheed', regex=True)
    .replace(r'^McDonnell.*', 'McDonnell Douglas', regex=True)
    .replace(r'^Pilatus.*', 'Pilatus', regex=True)
    .replace(r'^Raytheon.*', 'Raytheon', regex=True)
    .replace(r'^Rockwell.*', 'Rockwell', regex=True)
    .replace(r'^Saab.*', 'Saab', regex=True)
    .replace(r'^Shaanxi.*', 'Shaanxi', regex=True)
    .replace(r'^Shijiazhuang.*', 'Shijiazhuang', regex=True)
    .replace(r'^Shorts.*', 'Shorts', regex=True)
    .replace(r'^Swearingen.*', 'Swearingen', regex=True)
    .replace(r'^Viking.*', 'Viking', regex=True)
    
    )

In [66]:
flight_df["type"].value_counts()

type
Boeing                                   416
Cessna                                   366
Airbus                                   234
Antonov                                  184
Beechcraft                               172
                                        ...
North American Rockwell Sabreliner 60      2
de Havilland Canada DHC-8-202Q             2
Transall C-160NG                           2
Beriev Be-200ChS                           2
PZL-Mielec M28 Skytruck                    2
Name: count, Length: 76, dtype: int64

### 5. Data Analysis

Here we answer questions posed, that will help investors make decisions.

5.1 Find  5 top Flight 'Type' with most users